name: string_converter
description: A new Flutter package.
version: 0.0.1
author: Thit Lwin <thitlwincoder@gmail.com>
homepage: https://github.com/thitlwincoder/string_converter

environment:
  sdk: ">=2.7.0 <3.0.0"
